[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dao_reputation_scoreboard = "7ReputationDAOScoreboard11111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "7ReputationDAOScoreboard11111111111111111111"
program = "target/deploy/dao_reputation_scoreboard.so"

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
  { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
]